import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import {
  Assistant,
  Geist,
  Geist_Mono,
  Glory,
  Jost,
  Lato,
  Libre_Caslon_Display,
  Poppins,
} from "next/font/google";

import LayoutWrapper from "@/components/LayoutWrapper"; // client wrapper

// Fonts setup
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });
const jost = Jost({ variable: "--font-jost", weight: ["400", "600"], subsets: ["latin"] });
const poppins = Poppins({ variable: "--font-poppins", weight: ["400", "700"], subsets: ["latin"] });
const libreCaslonDisplay = Libre_Caslon_Display({ variable: "--font-libre-caslon-display", weight: "400", subsets: ["latin"] });
const glory = Glory({ variable: "--font-glory", weight: "400", subsets: ["latin"] });
const assistant = Assistant({ variable: "--font-assistant", weight: "400", subsets: ["latin"] });
const lato = Lato({ variable: "--font-lato", weight: "400", subsets: ["latin"] });

// Metadata (allowed in server components)
export const metadata: Metadata = {
  title: "Farm Natura",
  description: "Generated by create next app",
  icons: { icon: "/images/logo.png" },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${jost.variable} ${poppins.variable} ${libreCaslonDisplay.variable} ${glory.variable} ${assistant.variable} ${lato.variable} antialiased`}
      >
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
